### ISSUE TITLE
anti-captcha infinite loop when cloudflare has marked cipher invalid

### ISSUE THREAD

**Issue by HawkLiking** [VeNoMouS/cloudscraper#55] opened 2019-06-25 19:29 UTC
Hi, me again :P 

So I was trying to use anti-captcha.com with cloudscraper, but I have an issue

When I run my python script, it never exit, I have to stop it with CTRL+C. And the problem is that it seems that anti-captcha.com resolved the captcha, but the script is trying again and again... 
Here you can see that it is resolved, and all the captcha after this one were created in the same run (so the script tried 7 times, and then I stoped it)
[https://i.imgur.com/9QrqRMZ.png](https://i.imgur.com/9QrqRMZ.png)

When I stopped it, the output was:
```bash
^CTraceback (most recent call last):
  File "test.py", line 5, in <module>
    return cf.get(urlpage)
  File "/usr/local/lib/python3.5/dist-packages/requests-2.21.0-py3.5.egg/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 231, in sendChallengeResponse
    return self.request(resp.request.method, resp.url, **original_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 229, in sendChallengeResponse
    self.request(resp.request.method, submit_url, **cloudflare_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 157, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/__init__.py", line 198, in sendChallengeResponse
    params['g-recaptcha-response'] = reCaptcha.dynamicImport(self.recaptcha.get('provider').lower()).solveCaptcha(resp, self.recaptcha)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/reCaptcha/__init__.py", line 48, in solveCaptcha
    return self.getCaptchaAnswer(ret.url, site_key, reCaptchaParams)
  File "/usr/local/lib/python3.5/dist-packages/cloudscraper-1.1.19-py3.5.egg/cloudscraper/reCaptcha/anticaptcha.py", line 38, in getCaptchaAnswer
    job.join()
  File "/usr/local/lib/python3.5/dist-packages/python_anticaptcha/base.py", line 46, in join
    time.sleep(SLEEP_EVERY_CHECK_FINISHED)
KeyboardInterrupt
```

I am trying with this code 
```python
import cloudscraper

cf = cloudscraper.create_scraper(interpreter='nodejs', recaptcha={'provider': 'anticaptcha', 'api_key': 'XXXXXXXXXXXXXXXXXXXXXX'})

cf.get("https://pro-src.com/")
```

**Comment by HawkLiking** [comment] 2019-06-25 19:30
But maybe it is related to this issue https://github.com/VeNoMouS/cloudscraper/issues/54 !!!

**Comment by HawkLiking** [comment] 2019-06-25 19:42
If you need an anti-captcha API key, I can give you one @VeNoMouS :)

**Comment by VeNoMouS** [comment] 2019-06-26 02:37
This is def a bug ... but its a weird bug, its caused by the cipher being used.. I will def address this , but i cant for a couple days ... due to well... LIFE ;P the 1.1.20 push I'm sending through now should solve the reCaptcha 403 issue in the mean time, I'm sorry I cant resolve this loop for you straight away, but I have marked it as a bug and will address as fast as i can

**Closed** 2019-11-27 04:08 UTC
Labels: bug
