### ISSUE TITLE
ReCaptcha Proxy: True

### ISSUE THREAD

**Issue by NoahCardoza** [VeNoMouS/cloudscraper#176] opened 2020-03-29 19:48 UTC
After looking through the code, it appears all this means is that the request is made through the proxy, but 2captcha for instance, allows you to give them a proxy which they will solve the captcha from. Is/will that be supported? I'd be happy to submit a PR, at least for 2captcha, I don't have much experience with the other APIs.

https://2captcha.com/newapi-recaptcha-en

**Comment by VeNoMouS** [comment] 2020-03-29 23:25
Yea ill be overhauling the reCaptcha shortly im just waiting on anticaptcha to add some changes in there code.

this is actually a dupe of #126

**Closed** 2020-03-29 23:25 UTC
Labels: duplicate

**Comment by NoahCardoza** [comment] 2020-04-01 07:16
My bad, great to hear though!
