### ISSUE TITLE
cloudscraper can't solve some captchas

### ISSUE THREAD

**Issue by simonsruggi** [VeNoMouS/cloudscraper#86] opened 2019-11-12 16:46 UTC
I get 403 sometimes on this website because of captcha: 
You can test : https://www.43einhalb.com/adidas-yeezy-500-soft-vision-364709

**Comment by null-routed** [comment] 2019-11-12 18:11
Is the question something like "cloudscraper can't solve captchas even though I use captcha solving services"? The link has a hard captcha on it so cloudscraper is not gonna be able to go past it unless you provide a 2captcha/anticaptcha key.

**Comment by VeNoMouS** [comment] 2019-11-12 18:13
@simonsruggi are you re-using your cookies? Or constantly generating a scraper object in a loop? The latter will trigger cloudflare anti bot protection , can you give some more detail how you are making your requests ? Like some example code?

Cheers

**Comment by simonsruggi** [comment] 2019-11-12 18:20
@null-routed  Obviously i use a 2captcha api key and it works but not on that page.

@VeNoMouS :
Example code:

scraper = cloudscraper.create_scraper()

scraper.recaptcha= {'provider': '2captcha', 'api_key': apikey}

response = scraper.get(link, headers = headers)

print(response.status_code)  #which turns to be 403 on that specific captcha item

**Comment by VeNoMouS** [comment] 2019-11-12 18:22
What are headers? If you send wrong ordered headers, cf will reject you

**Comment by VeNoMouS** [comment] 2019-11-12 18:24
Re recaptcha , if that site has a recaptcha outside of cf and it’s embedded into the site, my module won’t solve that, it only solves when the recaptcha is presented by cf

**Comment by VeNoMouS** [comment] 2019-11-12 18:24
I’m not on my pc atm so I can’t look at it right now

**Comment by simonsruggi** [comment] 2019-11-12 18:26
headers = {
                'Host': 'www.43einhalb.com',
                'upgrade-insecure-requests': '1',
                'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36',
                'sec-fetch-user': '?1',
                'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
                'sec-fetch-site': 'same-origin',
                'sec-fetch-mode': 'navigate',
                'referer': 'https://www.43einhalb.com/adidas-yeezy-500-soft-vision-364709',
                'accept-language': 'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6,es;q=0.5',
            }

The captcha is from cloudflare:

https://www.43einhalb.com/cdn-cgi/l/chk_captcha?s=2f0a65dd72ed6b170e26439b0a25ccede786dfd4-1573582965-0-AWQVoIsPlUO60sNGqJ6aKwvTgHhI7ZwPchCh4S74KA6Tcgxuoef8TOtM%2BmaV93gk7gTomgYivoHW9ohkL%2BpsmPI8LGswB38gx%2BEoVDWm6PLEHX3PbPHHg%2BagRgQzyRKZ1AgNWVcWs9gkqL%2BCHPJ%2BL4ArDWzOQFpGdvfgjEyF%2BTlREXOQ7cOFfOvyfGblZ3w6MnYgMI7ElBi42A5UyrniSia1RJXcIjW12iuB3%2BsuG6BmZl%2BNhlREbYpvu2nKvxi0mA%3D%3D&id=534a887c682d3c81&g-recaptcha-response=03AOLTBLS9v3-Ch_j25L98LUsDdSxTI_RDHTDaS8rO_5F9CUyDQCKehkxZqzSSQe95C1ArtAUCFtGv09XZfLpGLKgx-8pP4vCCelGzGI5uPBo1wYScZqIfofCxDw3Cx76y_HegC5ZUFvEuO7GeYrC9LbjtEkcxpArenonJaFdry-4wiRJ35-0LEfQxgiCbORrlVkqNYo-WLpW078hmmiAufC3KYpYxTY-0i-dgXwGS5YYBsReYt8YC4y6vWh3kBtFjsfeeLiXmPNo9-uonI5mmd38VnttcVZsM9z979M9m4wGCBmWyGlCg3uqBXwK182tZUjk0Ktgi0kK37BEHo_w-AYdl70qq7UgnuEapdKD_zcob68hG5o7wzpPxR6fwMte_deg76dlbgw-etMNspnkLlQlYUK7LBz1gI_WC-qeR083fzVR65mCHMdLWLCs-NTYbFca7mGZuX6ccbVaoUXUDvW7Z3LAEvY9YJ_mO4E1sykgFG8OY70_7fd3WYPPprTcKPASpnDvmOhK0

**Comment by VeNoMouS** [comment] 2019-11-12 19:20
Your headers are not an ordered dict which will create your own issues, if you do

```python

import cloudscraper
from pprint import pprint

scraper = cloudscraper.create_scraper()
pprint(scraper.headers)
```

You'll see these are an ordered dict, a normal dict does not keep order of insert

The problem is most likely from you trying to manually set your own headers rather than the scrapers ones and doing it in correctly.

**Comment by VeNoMouS** [comment] 2019-11-12 19:27
Actually I tested this myself, and its reCaptcha on by default

```python
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper(debug=True)
>>> scraper.get('https://www.43einhalb.com/adidas-yeezy-500-soft-vision-364709')
< GET /adidas-yeezy-500-soft-vision-364709 HTTP/1.1
< Host: www.43einhalb.com
< User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:60.0) Gecko/20100101 Firefox/60.0.2
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate, br
< DNT: 1
<

> HTTP/1.1 403 Forbidden
> Date: Tue, 12 Nov 2019 19:22:14 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> CF-Chl-Bypass: 1
> Set-Cookie: __cfduid=d4eff3f2deab65b8b0c54a91b282ad0f01573586534; expires=Wed, 11-Nov-20 19:22:14 GMT; path=/; domain=.43einhalb.com; HttpOnly
> Cache-Control: max-age=2
> Expires: Tue, 12 Nov 2019 19:22:16 GMT
> X-Frame-Options: SAMEORIGIN
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 534adfa1ced5eea6-AKL
> Content-Encoding: br
```

Also looking at the site... its not actually detecting reCaptcha for some reason,

I need to investigate whats going on.

**Comment by simonsruggi** [comment] 2019-11-12 19:35
Basically the first request is always a 403 (because of captcha) but then, solving captcha and making a new request with new cf_clearance cookie you’ll get 200

**Comment by VeNoMouS** [comment] 2019-11-12 19:38
The actual problem appears that requests is not decoding the brotli even though I can see it ok in the debug, but when I access content or text attribute its encoded.. very strange bug I wonder if requests / urllib3 has a bug  , ill keep looking into it

**Comment by VeNoMouS** [comment] 2019-11-12 19:40
Upgrading urllib3 resolved issue for me , it now decodes and detects reCaptcha and solves correctly.

**Comment by simonsruggi** [comment] 2019-11-12 19:45
Thank you! Working now but i get this warning:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!

**Comment by VeNoMouS** [comment] 2019-11-12 19:45
upgrade your requests?

**Comment by VeNoMouS** [comment] 2019-11-12 19:47
I don't think https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L172 is working correctly

**Comment by simonsruggi** [comment] 2019-11-12 19:51
Thank you so much, everything is working smoothly now!

**Comment by VeNoMouS** [comment] 2019-11-12 19:59
Found the issue, https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L325 , since we super to requests and bypass our own hijack routine, we don't try decode brotli on earlier versions of urllib3, I will put in a fix for this

thanks for raising the issue @simonsruggi

**Comment by simonsruggi** [comment] 2019-11-12 20:13
Thank you for solving it

**Comment by VeNoMouS** [comment] 2019-11-12 20:55
@simonsruggi release 1.2.8 has been pushed to resolve for any one else that might come across the same problem.

Since you have upgraded you won't have this issue, as this is for people with urllib3 < 1.25.1 installed

**Closed** 2019-11-12 20:55 UTC
Labels: bug
