### ISSUE TITLE
Triggered Cloudflare_reCaptcha_Provider

### ISSUE THREAD

**Issue by wukongct** [VeNoMouS/cloudscraper#157] opened 2020-03-07 02:59 UTC
Thanks VeNoMouS for the great work. An application of mine seems to have been working well until earlier this week, when it often triggers the Cloudflare_reCaptcha_Provider exception. Manual retry on the same URL often goes through. Some context:
* Not using any proxy or tor network.
* Using the latest cloudscraper (1.2.26), and satisfied requirements (requests 2.22.0, requesets-toolbelt 0.9.1).
* The code is rate-limiting itself by waiting randomly a couple of seconds between requests.

I tried running with the `debug = True` option and copied the stacktrace below. 
https://pastebin.com/3RSXycv0

Many thanks in advance for any pointer you can give!

**Comment by VeNoMouS** [comment] 2020-03-07 03:22
I can see from your requests you have manually defined the headers wrong...

You should be defining the UA like...

```python
scraper = cloudscraper.create_scraper(
    browser={
        'custom': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.70 Safari/537.36'
    }
)
```

**Comment by VeNoMouS** [comment] 2020-03-07 03:25
Can i ask what what `interpreter` you have set on the scraper?

**Comment by wukongct** [comment] 2020-03-07 03:26
The interpreter is set to `native` and I'm running py3. Thanks - I'll give the above tip a shot.

**Comment by VeNoMouS** [comment] 2020-03-07 03:26
Windows? and what py3?

**Comment by wukongct** [comment] 2020-03-07 03:31
Running on WSL Ubuntu and python 3.7.4
```
~$ cat /proc/version
Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #476-Microsoft Fri Nov 01 16:53:00 PST 2019

~$ conda list | grep python
ipython                   7.11.1           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
msgpack-python            0.6.1            py37hfd86e86_1
python                    3.7.4                h265db76_1
python-dateutil           2.8.1                      py_0
python-libarchive-c       2.8                     py37_13
```

**Comment by VeNoMouS** [comment] 2020-03-07 08:13
mmmm what is the ssl that comes with that python?! do you get an SSL warning when you import cloudscraper?

**Comment by wukongct** [comment] 2020-03-07 19:08
Hmm no SSL warning:
```
~$ conda list | grep ssl
openssl                   1.1.1d               h7b6447c_3
pyopenssl                 19.1.0                   py37_0

~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> 
```

**Comment by wukongct** [comment] 2020-03-07 19:38
Interestingly, visiting the page with firefox leads shows contents properly, but URL has ?cf_chl_jschl_tk=<a long string>. Quick google search gives [this](https://community.cloudflare.com/t/url-of-website/132468/12).

**Comment by VeNoMouS** [comment] 2020-03-07 20:01
lol yes I am quite awake of the challenge url.. 

thank you for the coffee's ❤️ 

It seems odd that you're getting reCaptcha ... can you show me your scraper setup and get.. 

```python
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get('https://www.javlibrary.com/cn/?v=javli6j2sq')
<Response [200]>
>>>
```

**Comment by wukongct** [comment] 2020-03-07 22:15
Indeed the error seems transient - often a retry goes through happily as it did a couple of weeks ago. I'll tweak a bit more on rate limiting and maybe try on my Linux box. By the way, I don't actually get reCaptcha requesting `https://japscan.co`. Thanks for the pointers!

**Comment by VeNoMouS** [comment] 2020-03-10 21:50
Closing this for now, as I do not think the issue is with the module, more the fact that proxies are not being utilized and user is being detected for abuse by anti-bot by Cloudflare by issuing reCaptcha.

**Closed by VeNoMouS** 2020-03-10 21:50 UTC
