### ISSUE TITLE
!!Loop Protection!! on url redirect

### ISSUE THREAD

**Issue by ohura88** [VeNoMouS/cloudscraper#133] opened 2020-02-06 03:33 UTC
I'm finding that I'm getting an error `RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.` when I attempt to query a url that results in a redirect, using no configuration options.

The second url `http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340` redirects to `http://www.javlibrary.com/en/?v=javliilj4y` in a browser (and normally with cloudscraper), but I noticed just today that it started throwing that error instead.

Below is a snippet that illustrates the issue I'm running into. PS, sorry for the NSFW link

```>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper()
>>> url='http://www.javlibrary.com/en'
>>> contents = scraper.get(url).content.decode()
>>> url='http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340'
>>> contents = scraper.get(url).content.decode()
RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.```

**Comment by VeNoMouS** [comment] 2020-02-06 07:33
FWIW it works for me...

also `http://www.javlibrary.com/en` throws a 302 unless you end with /, however it still works for me...

I also noticed that on the second URL , it was trhowing in some redirects if you didnt goto `/?v=javliilj4y` this comes in the form of a 302..

```
> HTTP/1.1 302 Found
> Date: Thu, 06 Feb 2020 07:26:42 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: cf_clearance=c329942a05ef6ab3d91896c57636dc1d3ada1fb7-1580974001-0-150; path=/; expires=Fri, 07-Feb-20 08:26:41 GMT; domain=.javlibrary.com; HttpOnly
> X-Powered-By: PHP/5.5.20
> Last-Modified: Thu, 06 Feb 2020 07:26:32 GMT
> Expires: Mon, 26 Jul 1997 05:00:00 GMT
> Cache-Control: no-store, no-cache, must-revalidate
> Cache-Control: post-check=0, pre-check=0
> Pragma: no-cache
> Location: ./?v=javliilj4y
> CF-Cache-Status: DYNAMIC
> Server: cloudflare
> CF-RAY: 560b65b5f8daee96-AKL
>
<html><head>
<META HTTP-EQUIV=REFRESH CONTENT="0;URL=./?v=javliilj4y">
</head></html>

< GET /?v=javliilj4y HTTP/1.1
```

however if your using the cookies solved in the first request... it should all work properly...

```python
>>> import cloudscraper
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get('http://www.javlibrary.com/en/')
<Response [200]>
>>> scraper.get('http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340')
<Response [200]>
>>>
```

Please ensure you're using the latest version `1.2.20` and you're using the session scraper also fwiw im not sure why your using `decode()`

**Comment by pal0ntras** [comment] 2020-02-06 16:36
I am encounter same issue on above same urls, and I am using latest version `1.2.20`

I have the same program running on Windows, macOS 10.15 and Ubuntu 18.04, and strangely macOS and Ubuntu both works fine and Windows always failed with the error.
I am still examining the source of the cause.

**Comment by VeNoMouS** [comment] 2020-02-06 20:22
The whole "depth" thing, relates to how many times a redirect happens before hitting the end point from a challenge / solve.... 

the problem could be arising from https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L201 , 

specifally 

```python
if not resp.is_redirect
```

The fact these pages are serving up redirects straight away after the challenge...  it could blowing out the depth counter before you get a status code outside of 3xx and 4xx...

I would recommend doing what i suggested and increase the default solveDepth

```
python
scraper = cloudscraper.create_scraper(solveDepth=5)
```

**Comment by eckozen84** [comment] 2020-02-08 06:51
I have the same issue. I did my test using the same url above ''http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340'.
Response status is 200 but if you parse the html content I get:

```<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr/><center>cloudflare</center>
</body>
</html>
```

**Comment by VeNoMouS** [comment] 2020-02-08 07:19
The behaviour of the site has changed since the original opening ticket if you goto 
```
http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340
```

it will contentiously loops on CF challenge as there is no CFUID cookie...

besides, the sits logic is fucked, who 302's off CF to a 302.... pretty sure you're asking for too many redirects if coming in from other locations...

so i would recommend

```python
import cloudscraper
scraper = cloudscraper.create_scraper()

#populate cookies
scraper.get('http://www.javlibrary.com/')

# request page payload
content = scraper.get('http://www.javlibrary.com/en/vl_searchbyid.php?keyword=pppd-340').text
```

anyway, i'm not gonna answer thing more on this, as it works if you use basic logic to get around the sites restrictions, the problem is not the library.

**Comment by eckozen84** [comment] 2020-02-08 07:27
@VeNoMouS Thanks that works. I overlooked the previous post regarding storing cookies first. Apologies.

**Comment by pal0ntras** [comment] 2020-02-09 13:55
> The whole "depth" thing, relates to how many times a redirect happens before hitting the end point from a challenge / solve....
> 
> the problem could be arising from https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/__init__.py#L201
> 
> specifically
> 
> ```python
> if not resp.is_redirect
> ```
> 
> The fact these pages are serving up redirects straight away after the challenge... it could blowing out the depth counter before you get a status code outside of 3xx and 4xx...
> 
> I would recommend doing what i suggested and increase the default solveDepth
> 
> ```python
> scraper = cloudscraper.create_scraper(solveDepth=5)
> ```

Thanks, solveDepth actually solve the problem. Thanks for the work anyway

**Comment by VeNoMouS** [comment] 2020-02-10 01:35
Sorry guys, 

What I should've done was actually investigate further, I had a lot on when you guys filed this through,I have since investigated and confirmed its an actual bug... 

A fix is in currently in dev branch.

![image](https://user-images.githubusercontent.com/597545/74115144-8acc7980-4c12-11ea-9b9c-6f439c402c06.png)

**Comment by AmitGamingKing** [comment] 2020-02-13 13:35
same problem
```python
import cloudscraper
import ssl

#print(ssl.OPENSSL_VERSION)
scraper = cloudscraper.create_scraper(debug=True)
html = scraper.get("http://www17.animeultima.eu/search?search=death+note")
print(html)
```

output:
```
<some html code>

RuntimeError: !!Loop Protection!! We have tried to solve 3 time(s) in a row.
```

**Comment by VeNoMouS** [comment] 2020-02-13 20:36
@AmitGamingKing did you use the dev branch?

**Comment by VeNoMouS** [comment] 2020-02-14 01:32
The fix is now in production v1.2.22

**Closed by VeNoMouS** 2020-02-14 01:32 UTC
Labels: bug, question

**Comment by vrayv** [comment] 2020-02-14 07:20
Some sites are still not working. For example: https://www.ddlvalley.me/?s=civil

**Comment by VeNoMouS** [comment] 2020-02-14 07:21
Yea ive found another bug, on 302 redirects, just working on it atm

**Comment by VeNoMouS** [comment] 2020-02-14 07:54
@vrayv can you do me a favor and test the dev branch with the current `fix` in it..

**Comment by VeNoMouS** [comment] 2020-02-14 08:10
There is a small bug I need to work out...

when Location is starts with ./

```
> Location: ./?v=javliilj4y
```

**Comment by vrayv** [comment] 2020-02-14 08:38
Yup, the dev branch is working.

**Comment by VeNoMouS** [comment] 2020-02-15 02:05
Hi guys, Just pushed a better clean up fix , can you guys test what you need to test again please.

**Comment by vrayv** [comment] 2020-02-15 06:37
Works.
