### ISSUE TITLE
pyarmor support

### ISSUE THREAD

**Issue by leonswoosh** [VeNoMouS/cloudscraper#101] opened 2019-12-05 20:33 UTC
Cloudscraper is not compatible with pyarmor as of now?
Once packed & obfuscated you always get errors like this "FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/8t/2ln86pvj6dn5jzwk7s5hn7600000gn/T/_MEIMexGVA/cloudscraper/user_agent/browsers.json'"

Something is wrong with the dependencies I think..
You have any solution in mind?

**Comment by VeNoMouS** [comment] 2019-12-05 20:37
Most likely, you have to append data if its like some of the other packers... 

refer: https://github.com/VeNoMouS/cloudscraper/issues/72#issuecomment-524593291

**Comment by CoziestYew804** [comment] 2019-12-05 21:41
sorry to bother you again but when I pack your module I also get this error 
ERROR    invalid syntax (<frozen venv.lib.python3.7.site-packages.js2py.internals.speed>, line 50)

**Comment by VeNoMouS** [comment] 2019-12-05 22:02
i recommend using the current dev branch, it has a new python native solver for cloudflare that I wrote and removes the default requirement for js2py

**Comment by VeNoMouS** [comment] 2019-12-06 01:51
@CoziestYew804 how did you get on with this?

**Comment by CoziestYew804** [comment] 2019-12-06 14:14
@VeNoMouS seems to be solved if I don't install cloud scraper in a venv, maybe it's my python interpreter who's doing weird stuff

**Comment by CoziestYew804** [comment] 2019-12-06 18:10
@VeNoMouS here I am back to you LMAO. I first of all want to thank you for your wonderful work ! You're really active. Second, it came out the problem wasn't the fault of cloud scraper but was pyarmors fault. I fixed the fist issue by adding the cloud scraper folder as data in a .spec file and fixed the second issue by removing the venv environment but I think that I just could've add the js2py package as hidden import , anyway thank you again the problem is fixed now !

**Comment by VeNoMouS** [comment] 2019-12-06 21:21
awesome to hear your up and running mate :)

**Closed by VeNoMouS** 2019-12-06 21:21 UTC
Labels: Good question, not a bug
